# Generated by Django 3.0.4 on 2020-03-15 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database_test', '0002_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 15, 6, 37, 40, 81049, tzinfo=utc)),
        ),
    ]
