# Generated by Django 3.0.4 on 2020-03-15 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database_test', '0003_database_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 15, 6, 49, 25, 105978, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='database',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 15, 6, 49, 25, 52974, tzinfo=utc)),
        ),
    ]
