# Generated by Django 3.0.4 on 2020-03-15 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database_test', '0007_auto_20200315_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 15, 12, 3, 8, 394681, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employees',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 15, 12, 3, 8, 446685, tzinfo=utc)),
        ),
    ]
