# Generated by Django 3.0.4 on 2020-03-17 04:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database_test', '0008_auto_20200315_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 17, 4, 56, 15, 701892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employees',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 17, 4, 56, 15, 867314, tzinfo=utc)),
        ),
    ]
